# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Twin Cities Knowledge Management Forum
email: contact@tckmf.org
description: > # this means to ignore newlines until "baseurl:"
  Twin Cities Knowledge Management Forum exists to help members
  create and sustain business value through advancement of
  knowledge management practices within their organizations by
  sharing and learing together.  Minneapolis Saint Paul St. Paul
  Minnesota
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://test.nathanahlstrom.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
